name: hanzo
description: A library to easily use git hooks from Dart.
version: 1.0.2
homepage: https://github.com/andresaraujo/hanzo
author: Andres Araujo <a.araujo.azua@gmail.com>

environment:
  sdk: ">2.14.0 <3.0.0"

dependencies:
  args: ^2.3.0
  io: ^1.0.3
  build_cli: ^2.1.6
  build_cli_annotations: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.10
  test: ^1.3.0
  grinder: ^0.9.1

executables:
  hanzo: hanzo